# Generated by Django 5.2.1 on 2025-05-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('product_type', models.CharField(choices=[('Fragile', 'Fragile'), ('Liquid', 'Liquid')], max_length=10)),
                ('invoice_id', models.CharField(max_length=100)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Inside Dhaka', 'Inside Dhaka'), ('Division of Dhaka', 'Division of Dhaka'), ('Outside Dhaka', 'Outside Dhaka')], max_length=20)),
                ('cod_charge', models.FloatField(default=0)),
                ('return_charge', models.FloatField(default=0)),
                ('total_charge', models.FloatField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcel')),
            ],
        ),
    ]
